spring.application.name=users
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=stevejobs
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.root=INFO
logging.level.users.service.users=DEBUG

logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n

spring.rabbitmq.addresses=amqps://culhpuwq:l0nkAKjT5Zp8na0wnlAIHu2YsNySDJwe@possum.lmq.cloudamqp.com/culhpuwq
spring.rabbitmq.virtual-host=VHOST
spring.rabbitmq.ssl.enabled=true

