spring.application.name=atendimento

spring.datasource.url=jdbc:postgresql://localhost:5432/atendimentos
spring.datasource.username=postgres
spring.datasource.password=stevejobs
spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.service.atendimento.atendimento=DEBUG

logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n